import {MHeader,MIcon} from "../MobileMock";
const faqs=[
['Cos’è Schedly?','Schedly è un sistema per gestire gli appuntamenti della tua attività in un unico posto. Riunisce gestionale, calendario, clienti, servizi e booking online. Con Schedly AI puoi automatizzare anche le conversazioni di prenotazione su WhatsApp.'],
['A chi è rivolto Schedly?','È pensato per professionisti e piccole attività che lavorano su appuntamento: parrucchieri e barbieri, centri estetici, personal trainer, tattoo studio, consulenti e altre attività di servizi.'],
['Quali sono i principali vantaggi?','Hai agenda, clienti, servizi e disponibilità centralizzati. Riduci il tempo dedicato a messaggi e organizzazione e, con Schedly AI, puoi automatizzare richieste di disponibilità, prenotazioni, modifiche e cancellazioni.'],
['Serve installare un software?','No. Schedly è un servizio web: accedi dal browser e puoi usarlo da computer, tablet o smartphone.'],
['Posso provarlo prima di acquistare?','Sì. Dalla Home puoi avviare una prova gratuita di 7 giorni. Non serve una carta di credito e la prova è disponibile una sola volta per attività.'],
['Come funziona l’assistente WhatsApp AI?','Il cliente scrive su WhatsApp, l’assistente interpreta la richiesta, consulta le disponibilità gestite da Schedly e può proporre orari, creare un appuntamento oppure gestire una modifica o una cancellazione.'],
['Cosa include la configurazione iniziale?','La configurazione iniziale include l’impostazione di servizi, orari, disponibilità e principali preferenze della tua attività. Con Schedly AI viene configurato anche l’assistente per il flusso WhatsApp.'],
['Posso cambiare piano in un secondo momento?','L’offerta è pensata per permetterti di partire dal gestionale Schedly e aggiungere l’automazione AI quando ne hai bisogno. Le condizioni operative definitive saranno indicate durante l’attivazione.'],
['Quali metodi di pagamento accettate?','I pagamenti dell’abbonamento saranno gestiti online tramite Stripe. I metodi effettivamente disponibili dipenderanno da quelli abilitati al momento dell’attivazione.'],
['È previsto un vincolo di durata?','Le condizioni di rinnovo e cancellazione saranno indicate in modo trasparente prima dell’attivazione del servizio.'],
['I miei dati sono al sicuro?','Schedly è progettato con autenticazione, separazione dei dati tra attività e protezioni applicative. I dettagli completi su trattamento, conservazione e privacy saranno descritti nella documentazione legale del servizio.'],
['Cosa succede se ho bisogno di aiuto?','Il piano Schedly prevede supporto email; Schedly AI include supporto prioritario. Durante la configurazione iniziale ti aiutiamo anche a impostare correttamente il servizio.']
];
export default function FAQ(){return <><main className="mobileMock mFaqPage"><MHeader/><p className="mEyebrow">FAQ</p><h1>Hai domande?<br/>Abbiamo <span className="mBlue">le risposte.</span></h1><p className="mLead">Qui trovi le risposte alle domande più frequenti su Schedly.</p><div className="mFaq">{faqs.slice(0,8).map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><div className="mBottomCard"><div className="mInfoCard" style={{margin:0,border:0,boxShadow:"none",padding:0}}><span className="mIcon mPurple"><MIcon type="help"/></span><div><b>Pronto a iniziare?</b><p>Puoi creare un account oppure avviare la prova gratuita dalla Home.</p></div></div><a className="mBtn" href="/registrati">Registrati →</a></div></main><main className="page faqPage faqApproved desktopOnly"><header className="siteNav"><a className="brand" href="/"><span className="brandMark"><span className="logoCal"/><span className="logoCheck">✓</span></span><span>Schedl<span className="brandY">y</span></span></a><nav><a href="/prodotto">Prodotto</a><a href="/come-funziona">Come funziona</a><a href="/prezzi">Prezzi</a><a className="active" href="/faq">FAQ</a></nav><div><a href="/login">Accedi</a><a className="button buttonSmall" href="/registrati">Registrati</a></div></header><section className="pageHero centered"><p className="eyebrow">FAQ</p><h1>Hai domande?<br/><span>Abbiamo le risposte.</span></h1><p>Tutto quello che devi sapere su Schedly, in modo semplice e trasparente.</p></section><section className="faqList">{faqs.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<b>+</b></summary><p>{x[1]}</p></details>)}</section><section className="darkCta"><p>PRONTO A INIZIARE?</p><h2>Crea il tuo account Schedly.</h2><a className="button light" href="/registrati">Registrati →</a></section></main></>}
