import MobileMenu from "./MobileMenu";
import {MHeader,PhoneArt,MIcon} from "./MobileMock";
const Logo=()=> <a className="brand homeBrand" href="/" aria-label="Schedly"><img className="officialLogo" src="/schedly-logo.png" alt="Schedly" /></a>;
const Bot=()=> <span className="bot" aria-hidden="true"><img src="/schedly-logo.png" alt="" /></span>;
const HorizontalLogo=({compact=false}:{compact?:boolean})=> <span className={compact?"horizontalLogo compact":"horizontalLogo"} aria-label="Schedly"><span className="horizontalLogoIcon"><img src="/schedly-logo.png" alt="" /></span><span className="horizontalLogoWord"><img src="/schedly-logo.png" alt="" /></span></span>;\nconst ProductBrand=()=> <HorizontalLogo compact/>;
const Dashboard=()=> <div className="dashPreview"><aside><b><Bot/> Schedly</b><span>▣ Dashboard</span><span>▣ Calendario</span><span>▣ Appuntamenti</span><span>♟ Clienti</span><span>▣ Servizi</span><span>◷ Disponibilità</span><span>▥ Statistiche</span><span>◉ Messaggi</span><span>⚙ Impostazioni</span></aside><div className="dashBody"><div className="dashTop"><b>Dashboard</b><div className="dashSearch">⌕ &nbsp; Cerca clienti, appuntamenti...</div><button>+ Nuovo appuntamento</button></div><div className="kpis"><b>Appuntamenti oggi<br/><strong>12</strong><small>↗ 20%</small></b><b>Nuovi clienti<br/><strong>8</strong><small>↗ 12%</small></b><b>Fatturato<br/><strong>€ 320</strong><small>↗ 18%</small></b><b>Tasso di conferma<br/><strong>96%</strong><small>↗ 4%</small></b></div><div className="nextHead"><h4>Prossimi appuntamenti</h4><span>›</span></div><div className="dashRows"><p><i className="rowBlue">▣</i><b>10:30</b><span>Laura Bianchi</span><em>Piega</em></p><p><i className="rowPurple">▣</i><b>11:00</b><span>Marco Rossi</span><em>Taglio</em></p><p><i className="rowPink">▣</i><b>12:00</b><span>Giulia Verdi</span><em>Colore</em></p><p><i className="rowOrange">▣</i><b>14:30</b><span>Luca Ferrari</span><em>Barba</em></p><p><i className="rowGreen">▣</i><b>16:30</b><span>Martina Conti</span><em>Trattamento</em></p></div></div></div>;
export default function Home(){return <><main className="mobileMock mHomePage"><MHeader/><p className="mEyebrow mPill">PIÙ TEMPO PER CIÒ CHE CONTA</p><h1>La tua attività,<br/><span className="mBlue">più semplice.</span></h1><p className="mLead">Schedly organizza agenda, clienti e prenotazioni in un unico posto. Con Schedly AI, anche WhatsApp può lavorare per te.</p><a className="mBtn" href="/demo">Prova gratis 7 giorni →</a><p className="mNote">Nessuna carta di credito richiesta.</p><PhoneArt home/><div className="mInfoCard"><span className="mIcon mYellow"><MIcon type="bolt"/></span><div><b>Pensato per professionisti come te</b><p>Più tempo per i tuoi clienti, meno tempo davanti al computer.</p></div></div>
<section className="mHomeProduct"><p className="mEyebrow">IL PRODOTTO</p><h2>Tutto ciò che ti serve, <span className="mBlue">in un unico posto.</span></h2><p className="mLead">Schedly è il gestionale per agenda, clienti, servizi e prenotazioni. Schedly AI aggiunge l’assistente WhatsApp 24/7.</p><div className="mFeatureList"><div className="mFeatureCard"><span className="mIcon mBlueBg"><MIcon type="dashboard"/></span><div><b>Gestionale completo</b><p>Agenda, clienti, servizi, disponibilità e prenotazioni sempre ordinati.</p></div></div><div className="mFeatureCard"><span className="mIcon mGreen"><MIcon type="whatsapp"/></span><div><b>WhatsApp con AI</b><p>Solo con Schedly AI: risposte, prenotazioni, modifiche e cancellazioni automatiche.</p></div></div><div className="mFeatureCard"><span className="mIcon mYellow"><MIcon type="bell"/></span><div><b>Promemoria automatici</b><p>Riduci le assenze senza rincorrere i clienti.</p></div></div></div><a className="mTextLink" href="/prodotto">Scopri il prodotto →</a></section>
<section className="mPlanCompare"><p className="mEyebrow">DUE MODI DI USARE SCHEDLY</p><h2>Parti dal gestionale. <span className="mBlue">Automatizza quando vuoi.</span></h2><div className="mCompareGrid"><article className="mCompareCard"><span className="mCompareIcon mBlueBg"><MIcon type="calendar"/></span><div className="mCompareCopy"><small>SCHEDLY</small><b>Il tuo gestionale</b><p>Agenda, clienti, servizi, booking online e promemoria.</p></div><a href="/prezzi">Da €29,90/mese →</a></article><article className="mCompareCard ai"><span className="mCompareIcon mPurple"><MIcon type="bolt"/></span><div className="mCompareCopy"><small>SCHEDLY AI</small><b>Il gestionale + WhatsApp AI</b><p>Tutto Schedly, più un assistente che gestisce le prenotazioni su WhatsApp 24/7.</p></div><a href="/prezzi">Da €49,90/mese →</a></article></div></section>
<section className="mDashboardSection"><p className="mEyebrow">LA TUA DASHBOARD</p><h2>Vedi tutto. <span className="mBlue">A colpo d'occhio.</span></h2><p className="mLead">Questa è la schermata da cui controlli appuntamenti, clienti e andamento della tua attività.</p><div className="mDashboardMock"><div className="mDashBar"><b>Dashboard</b><span>•••</span></div><div className="mDashStats"><div><small>Oggi</small><b>12</b><em>appuntamenti</em></div><div><small>Clienti</small><b>8</b><em>nuovi</em></div></div><div className="mDashTitle"><b>Prossimi appuntamenti</b><small>Oggi</small></div><div className="mDashRow"><i/><b>10:30</b><span>Laura Bianchi<small>Piega</small></span><em>Confermato</em></div><div className="mDashRow"><i/><b>11:00</b><span>Marco Rossi<small>Taglio</small></span><em>Confermato</em></div><div className="mDashRow"><i/><b>14:30</b><span>Giulia Verdi<small>Colore</small></span><em>Confermato</em></div></div><a className="mBtn" href="/demo">Prova Schedly gratis per 7 giorni →</a><p className="mNote">Nessuna carta di credito richiesta.</p></section></main><main className="home mockHome desktopOnly homeV4">
<section className="v4Hero">
<nav className="nav v4Nav"><a className="v4OfficialLogo" href="/" aria-label="Schedly"><HorizontalLogo/></a><div className="navLinks"><a href="/prodotto">Prodotto</a><a href="/come-funziona">Come funziona</a><a href="/prezzi">Prezzi</a><a href="/faq">FAQ</a><a href="/blog">Blog</a></div><div className="navActions"><a href="/login">Accedi</a><a className="v4Trial" href="/demo">Prova gratis 7 giorni</a></div></nav>
<div className="v4HeroInner">
<div className="v4Copy"><p className="v4Eyebrow">PER CHI LAVORA SU APPUNTAMENTO</p><h1>Mentre lavori,<br/><span>Schedly</span> prende<br/>gli appuntamenti.</h1><p className="v4Lead">Agenda, clienti, servizi e disponibilità.<br/>I tuoi clienti prenotano online e, con Schedly AI,<br/>anche su WhatsApp.</p><a className="v4MainCta" href="/demo">Prova gratis 7 giorni</a><p className="v4NoCard">Nessuna carta di credito richiesta.</p><div className="v4Checks"><span>✓ <b>Attivazione in pochi minuti</b></span><span>✓ <b>Nessun vincolo</b></span><span>✓ <b>Assistenza sempre inclusa</b></span></div></div>
<div className="v4Visual">
<div className="v4Laptop"><div className="v4LaptopTop"><ProductBrand/><div className="v4Search">⌕ &nbsp; Cerca clienti, servizi...</div><span>♧</span><b>SM</b></div><div className="v4LaptopBody"><aside><strong>⌂ &nbsp; Dashboard</strong><strong className="active">▣ &nbsp; Agenda</strong><strong>♙ &nbsp; Clienti</strong><strong>⌘ &nbsp; Servizi</strong><strong>▣ &nbsp; Prenotazioni</strong><strong>♧ &nbsp; Promemoria</strong><strong>◉ &nbsp; Messaggi</strong><strong>▥ &nbsp; Statistiche</strong><strong>⚙ &nbsp; Impostazioni</strong></aside><div className="v4Agenda"><div className="v4AgendaHead"><h3>Agenda</h3><div><button>Oggi</button><button>›</button><small>Mercoledì 14</small></div></div><div className="v4Week"><div className="v4Times"><i>08:00</i><i>09:00</i><i>10:00</i><i>11:00</i><i>12:00</i><i>13:00</i><i>14:00</i><i>15:00</i><i>16:00</i><i>17:00</i><i>18:00</i></div><div className="v4Day"><b>Cliente A</b><span className="blue">09:00<br/>Taglio</span><span className="pink">10:30<br/>Piega</span><span className="purple">12:00<br/>Colore</span></div><div className="v4Day"><b>Cliente B</b><span className="green">09:30<br/>Barba</span><span className="blue second">11:00<br/>Taglio</span><span className="yellow">15:00<br/>Trattamento</span></div><div className="v4Day"><b>Cliente C</b><span className="pink second">10:00<br/>Manicure</span><span className="purple third">14:00<br/>Pedicure</span><span className="green fourth">16:30<br/>Semipermanente</span></div></div></div><div className="v4Side"><h4>Oggi</h4><div className="v4MiniCal">L M M G V S D<br/><b>12 13 14 15 16 17 18</b></div><h4>Prossimi appuntamenti</h4><p><b>09:00</b> Cliente A<br/><small>Taglio</small></p><p><b>10:30</b> Cliente B<br/><small>Barba</small></p><p><b>12:00</b> Cliente C<br/><small>Piega</small></p><p><b>15:00</b> Cliente D<br/><small>Trattamento</small></p></div></div></div>
<div className="v4Phone"><div className="v4PhoneHead"><span>9:41</span><b>● Schedly</b><i>⌕</i></div><div className="v4Wa"><p className="me">Ciao! Posso prenotare una piega per domani mattina?</p><p>Certo! Ho disponibilità alle 9:00, 10:30 e 11:00. Quale preferisci?</p><p className="me">Perfetto, 10:30!</p><p>Fatto! ✅<br/>Appuntamento confermato per domani alle 10:30.<br/>A presto!</p></div><div className="v4PhoneInput">Scrivi un messaggio... <b>➤</b></div></div>
</div></div></section>
<section className="v4Features"><article><i className="fi calendarIcon" aria-hidden="true"></i><div><b>Prenotazioni online</b><p>I clienti prenotano quando vogliono, anche fuori orario.</p></div></article><article><i className="fi peopleIcon" aria-hidden="true"></i><div><b>Agenda sempre aggiornata</b><p>Ogni prenotazione compare direttamente nella tua agenda.</p></div></article><article><i className="fi waIcon" aria-hidden="true">◉</i><div><b>WhatsApp AI opzionale</b><p>Un assistente che risponde e gestisce le prenotazioni.</p></div></article><article><i className="fi bellIcon" aria-hidden="true"></i><div><b>Promemoria automatici</b><p>Meno assenze, più tempo per la tua attività.</p></div></article></section>
<section className="v4Industries"><p>PENSATO PER CHI LAVORA SU APPUNTAMENTO</p><div><span>✂ <b>Parrucchieri e barbieri</b></span><span>✿ <b>Centri estetici</b></span><span>◫ <b>Personal trainer</b></span><span>♧ <b>Studi medici e dentistici</b></span><span>✎ <b>Nail artist</b></span><span>••• <b>e molti altri...</b></span></div></section>
</main></>}