const Logo=()=> <a className="brand" href="/" aria-label="Schedly"><img className="officialLogo" src="/schedly-logo.png" alt="Schedly" /></a>;
const Avatar=()=> <span className="howAvatar">👩🏻</span>;
export default function ComeFunziona(){return <main className="page howPage howApproved">
<header className="siteNav"><Logo/><nav><a href="/prodotto">Prodotto</a><a className="active" href="/come-funziona">Come funziona</a><a href="/prezzi">Prezzi</a><a href="/faq">FAQ</a></nav><div><a href="/login">Accedi</a><a className="button buttonSmall" href="/demo">Richiedi una demo →</a></div><span className="howMenu">☰</span></header>
<section className="howTop"><div className="howTopCopy"><p className="eyebrow">COME FUNZIONA</p><h1>Dal messaggio<br/><span>all’appuntamento.</span></h1><p>Schedly gestisce l’intero processo, dal primo messaggio alla conferma, in modo automatico. Tu pensi al tuo lavoro, al resto ci pensa l’AI.</p><a className="button" href="/demo">Richiedi una demo　→</a></div><div className="howTopVisual"><div className="howIcon wa">◉</div><div className="howIcon ai"><img src="/schedly-logo.png" alt=""/></div><div className="howIcon calIcon">▦</div><i className="arc a1"/><i className="arc a2"/><div className="scribble topScribble">Un processo semplice.<br/>Risultati reali. ↘</div><div className="scribble happyScribble">Clienti più felici.<br/>Più tempo per te.</div></div></section>
<section className="howJourney">
<article className="journeyRow"><div className="journeyNo">01</div><div className="journeyCopy"><b>IL CLIENTE SCRIVE</b><h2>Un messaggio<br/>su WhatsApp.</h2><p>Il tuo cliente ti scrive su WhatsApp con una richiesta, una domanda o per prenotare un appuntamento.</p></div><div className="journeyVisual first"><Avatar/><div className="msg customerMsg">Ciao, avete disponibilità<br/>domani pomeriggio?<small>10:24 ✓✓</small></div><span className="waBubble">●</span></div></article>
<article className="journeyRow"><div className="journeyNo">02</div><div className="journeyCopy"><b>L’AI DI SCHEDLY RISPONDE</b><h2>L’assistente AI<br/>capisce e propone.</h2><p>Schedly interpreta la richiesta, verifica la disponibilità nella tua agenda e propone subito le opzioni migliori, in modo naturale.</p></div><div className="journeyVisual"><span className="aiBadge"><img src="/schedly-logo.png" alt=""/></span><div className="msg aiMsg">Certo! Ho trovato queste<br/>disponibilità per domani:<div className="slotRow"><span>15:00</span><b>16:30</b><span>18:00</span></div><small>10:25</small></div></div></article>
<article className="journeyRow"><div className="journeyNo">03</div><div className="journeyCopy"><b>IL CLIENTE CONFERMA</b><h2>L’appuntamento<br/>è confermato.</h2><p>Il cliente sceglie l’orario e Schedly conferma l’appuntamento, fornendo eventuali informazioni utili (indirizzo, servizi, ecc).</p></div><div className="journeyVisual confirmVisual"><Avatar/><div className="msg customerMsg short">Perfetto, 16:30!<small>10:26 ✓✓</small></div><span className="aiBadge lower"><img src="/schedly-logo.png" alt=""/></span><div className="msg aiMsg confirm">Fatto! ✅<br/>Ti aspetto domani alle 16:30.<br/>A presto!<small>10:26</small></div><i className="accentLines">╱╱</i></div></article>
<article className="journeyRow last"><div className="journeyNo">04</div><div className="journeyCopy"><b>L’AGENDA SI AGGIORNA</b><h2>Tutto sincronizzato,<br/>in tempo reale.</h2><p>L’appuntamento viene inserito automaticamente nella tua agenda, con il cliente, il servizio e tutte le informazioni. Tu non devi fare nulla.</p></div><div className="journeyVisual calendarVisual"><div className="miniCalendar"><span className="time">15:00<br/><br/>16:00<br/><br/>17:00<br/><br/>18:00</span><div className="calendarEvent"><Avatar/><div><b>Giulia Rossi</b><small>Taglio</small></div><strong>✓</strong></div></div><div className="scribble updated">Aggiornato<br/>automaticamente. ↙</div></div></article>
</section>
<section className="howBottomCta"><div><p>MENO MESSAGGI. PIÙ TEMPO PER TE.</p><h2>Lascia che Schedly<br/>gestisca i tuoi appuntamenti.</h2><span>Richiedi una demo gratuita e scopri come può aiutarti a far crescere la tua attività.</span></div><div className="ctaForm"><div><input placeholder="La tua email" type="email"/><a href="/demo">Richiedi una demo　→</a></div><small>✓　Nessun impegno　　 ✓　Attivazione rapida　　 ✓　Assistenza inclusa</small></div></section>
</main>}
